language: python
python: "3.6"

branches:
  only:
    - master

env:
  # Github Pages
  - GH_REF: github.com/CoderTonyChan/USTC-Course

install:
  - pip install --upgrade pip
  - pip install flake8 markdown pypinyin

script:
  - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
  - python utils/genReadme.py
  - python utils/genIndex.py

after_script:
  # Build Master Repository(Coding Pages) 
  - git config user.name "CoderTonyChan"
  - git config user.email "101992315@qq.com"
  - cd docs
  - git init
  - git remote add origin git@github.com:CoderTonyChan/USTC-Course.git
  - git add --all
  - git commit -m "Travis-CI Update pages with build $TRAVIS_BUILD_NUMBER"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

notifications:
  email:
    recipients:
      - hi@tonystudio.ml
    on_success: change # default: change
    on_failure: always # default: always
